Python 3 compatibility (pyprof2calltree.py)
Fixes the following exception when converting Python profiling data to the callgrind format:

```
Traceback (most recent call last):
  File "pyprof2calltree", line 9, in <module>
    load_entry_point('pyprof2calltree==1.3.0', 'console_scripts', 'pyprof2calltree')()
  File "pyprof2calltree.py", line 290, in main
    kg.output(open(outfile, 'wb'))
  File "pyprof2calltree.py", line 130, in output
    out_file.write('events: Ticks\n')
TypeError: 'str' does not support the buffer interface
```